### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by ranisalt** [maikeps/fractality#1]
```
Traceback (most recent call last):
  File "fractality.py", line 3, in <module>
    import tkinter
  File "/usr/lib/python3.4/tkinter/__init__.py", line 38, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
ImportError: libtk8.6.so: cannot open shared object file: No such file or directory
```

What libraries need to be installed to run the script?

**Comment by Amatsukan** [comment]
You must install Tkinter.
Tkinter lib is responsible for making all the graphical part...

https://wiki.python.org/moin/TkInter
